Feature/fdp 1815
OSGP/sng-crest-device-simulator pull request #12
Opened 2024-01-25 13:16 UTC by LucianoFavoroso

2024-01-25 17:29 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskKeyExtractor.kt
> +    private val pskKeyHashSplitterRegex = "(?<=PSK:)([a-zA-Z0-9]{16})([a-zA-Z0-9]{64})".toRegex()
Je kunt de twee RegEx-en ook combineren, dan kunnen de validatie en splitter nooit afwijken van elkaar

2024-01-25 17:29 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskKeyExtractor.kt
>  class PskKeyExtractor {
Kan ook als `object` ipv @Component. Er wordt namelijk niets anders ge-inject

2024-01-25 17:29 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/command/PskCommandHandler.kt
> +            throw PskHashNotValidException()
Ik mis hier wel een message met daarin bijv. de identity

2024-01-25 17:32 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/command/PskCommandHandler.kt
> +        val expectedHash = DigestUtils.sha256Hex("${secret}${newPsk}")
`$...` kan zonder `{}`

2024-01-29 11:12 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskKeyExtractor.kt
> +    private val pskKeyHashSplitterRegex = "!PSK:([a-zA-Z0-9]{16})([a-zA-Z0-9]{64});PSK:([a-zA-Z0-9]{16})([a-zA-Z0-9]{64})SET".toRegex()
Die 3e en 4e groep hoeven niet, worden nooit gebruikt

2024-01-29 12:44 UTC, sanderv approved these changes

2024-01-30 09:56 UTC, smvdheijden requested changes

2024-01-30 09:56 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/command/exception/PskHashNotValidException.kt
> +class PskHashNotValidException(message: String) : Exception(message)
I think I prefer `InvalidPskHashException` over the current name.

2024-01-30 09:56 UTC, smvdheijden commented on application/src/main/resources/db/migration/V2__secret.sql
> +-- No production data was set before this change so we can drop all existing data
Include copyright header?

2024-01-30 09:56 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskExtractorTest.kt
> +package org.gxf.crestdevicesimulator.simulator.response
Include copyright header.

2024-01-30 09:56 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskExtractorTest.kt
> +    fun shouldReturnTrueWhenThereIsAPskCommandInString() {
Consider making this a parameterized test.

2024-01-30 09:56 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskExtractorTest.kt
> +    fun shouldReturnPskKeyFromValidPskCommand() {
Consider making this a parameterized test.

2024-01-30 09:56 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskExtractorTest.kt
> +        assertFalse(resultNoPskCommand)
Use AssertJ assertions.

2024-01-30 09:56 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskExtractorTest.kt
> +        assertEquals("PSKaSET1PSKd2SET", resultValidWithKeyWords)
Use AssertJ assertions.

2024-01-30 09:56 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/command/PskCommandHandler.kt
> +class PskCommandHandler(private val pskRepository: PskRepository,
Consider adding unit tests for this class

2024-01-30 09:56 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskExtractorTest.kt
> +class PskExtractorTest {
Add test for hash as well?

2024-01-30 12:19 UTC, sanderv approved these changes

2024-01-30 15:08 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskExtractor.kt
> +    fun extractHashFromCommand(command: String) = pskKeyHashSplitterRegex.findAll(command).first().groups[2]!!.value
I would rather have one regex findAll instead of 2 but for the simulator this could be good enough

2024-01-30 15:08 UTC, jasperkamerling approved these changes

2024-01-30 15:50 UTC, smvdheijden requested changes

2024-01-30 15:50 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdevicesimulator/simulator/response/command/PskCommandHandlerTest.kt
> +    private val key = "1234567891234567"
I would expect to see an old and a new key in this test.

2024-01-30 15:50 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdevicesimulator/simulator/response/command/PskCommandHandlerTest.kt
> +        `when`(pskRepository.findById(any())).thenReturn(Optional.of(PreSharedKey(identity, key, secret)))
Here return a PSK with an old key

2024-01-30 15:50 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdevicesimulator/simulator/response/command/PskCommandHandlerTest.kt
> +        }
I would prefer to have separate sections for act and assert.
Consider adding some verification that both repository and store are not changed as well.

2024-01-30 15:50 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdevicesimulator/simulator/response/command/PskCommandHandlerTest.kt
> +}
Add newline at end of file

2024-02-01 08:03 UTC, smvdheijden approved these changes

2024-02-01 08:20 UTC, sanderv approved these changes

2024-02-01 08:20 UTC, merged