Feature/fdp 1961 psk change flow
OSGP/sng-crest-device-simulator pull request #16
Opened 2024-03-20 12:27 UTC by loesimmens

2024-03-26 10:24 UTC, JelleHoffman requested changes
I am missing documentation, on method level but also on generic change flow level.

2024-03-27 08:29 UTC, LucianoFavoroso approved these changes

2024-03-27 08:29 UTC, LucianoFavoroso commented on application/src/main/resources/messages/psk-change-failure-message.json
> +      "DL": "!PSK:SET"
Klopt dit veld? Moet hier niet de gehele voorgaande Downlink staan?

2024-03-27 08:29 UTC, LucianoFavoroso commented on settings.gradle.kts
> +            ).versionRef("mockitoKotlin")
Version ref niet persee nodig we gebruiken maar 1 5.3.0

2024-03-27 08:34 UTC, JelleHoffman approved these changes

2024-03-27 16:25 UTC, smvdheijden requested changes

2024-03-28 11:05 UTC, loesimmens commented on settings.gradle.kts
> +            ).versionRef("mockitoKotlin")
Oei, ik weet niet hoe ik dan aan 5.3.0 kom, ik heb er 5.1.0 van gemaakt, zoals in andere services

2024-03-28 11:11 UTC, loesimmens commented on application/src/main/resources/messages/psk-change-failure-message.json
> +      "DL": "!PSK:SET"
Dat kan niet in een json, omdat er altijd een andere nieuwe key zal staan (random gegenereerd door de crest-device-service). Deze algemene tekst wordt wel vervangen door de echte ontvangen downlink in https://github.com/OSGP/sng-crest-device-simulator/blob/cbdc594c8ccd826990671b37e4a97758f6f39194/application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/message/MessageHandler.kt#L103

2024-04-02 13:51 UTC, LucianoFavoroso approved these changes

2024-04-02 16:12 UTC, jasperkamerling approved these changes

2024-04-02 16:16 UTC, merged

2024-04-02 16:31 UTC, smvdheijden commented on settings.gradle.kts
> +            ).versionRef("mockitoKotlin")
There seems to be a 5.3.0 version available in GitHub, but probably it is not yet available in the repositories we use.