FDP-2318: Spotless including pre-commit githook
OSGP/sng-crest-device-simulator pull request #35
Opened 2024-09-16 14:44 UTC by loesimmens

2024-09-16 16:24 UTC, smvdheijden requested changes

2024-09-16 16:24 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskExtractor.kt
> +     * chars after the key this is only the hash
Hmm, this looks pretty ugly... :disappointed: 

Try to increase the readability of this comment.

2024-09-17 11:11 UTC, smvdheijden approved these changes

2024-09-17 12:57 UTC, sanderv approved these changes

2024-09-17 12:59 UTC, merged