FDP-1628: made psk changeable
OSGP/sng-crest-device-simulator pull request #5
Opened 2023-11-15 14:38 UTC by LucianoFavoroso

2023-11-16 20:09 UTC, smvdheijden requested changes
Missing license headers

2023-11-16 20:09 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/ResponseHandler.kt
> +        pskRepository.save(current.get().apply { key = newPsk })
This will save the key, but will not make it available yet in the pskStore?

2023-11-21 08:35 UTC, LucianoFavoroso commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/ResponseHandler.kt
> +        pskRepository.save(current.get().apply { key = newPsk })
Correct it works for now. The only time the key is used when the first connection is made, wich only happens on startup. This can change in the future, its a small change, so i will implement it now.

2023-11-21 10:50 UTC, JelleHoffman approved these changes

2023-11-21 13:15 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/configuration/CoapClientConfiguration.kt
> +    fun getClient(dtlsConnector: DTLSConnector): CoapClient {
Je Bean heet nu `getClient`, ook hier kun je een beschrijvender naam verzinnen

2023-11-21 13:15 UTC, sanderv commented on application/src/main/resources/db/migration/V1__psk.sql
> +    primary key (identity)
Naamgeving is hier wel verwarend. "Wat is de key van psk?"

2023-11-27 08:26 UTC, LucianoFavoroso commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/ResponseHandler.kt
> +        pskRepository.save(current.get().apply { key = newPsk })
This issue is solved. Github does not show it as outdated. Will mark comment as resolved.

2023-11-27 11:50 UTC, sanderv approved these changes

2023-12-01 17:32 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdevicesimulator/simulator/response/PskKeyExtractor.kt
>  class PskKeyExtractor {
- The PSKs should consist of alphanumeric characters only.
- The first regex seems to be a subset of the second, hence will always be true if the second one is true (and is therefore not needed in the `hasPskCommand` function)?
- For a check on a complete combined PSK command you should probably check with a regex like `PSK:[a-zA-Z0-9]{16};PSK:[a-zA-Z0-9]{16}SET`.
- Since both functions contain just a single-line they could be written as one-expression functions.

Considering the above, I think the class content could become something like this:
```kotlin
    private val pskCommandVerificationRegex = "PSK:[a-zA-Z0-9]{16};PSK:[a-zA-Z0-9]{16}SET".toRegex()
    private val pskExtractorRegex = "(?<=PSK:)[a-zA-Z0-9]{16}".toRegex()
    
    fun hasPskCommand(command: String) = pskCommandVerificationRegex.matches(command) 

    fun extractKeyFromCommand(command: String) = pskExtractorRegex.findAll(command).first().value
```

2023-12-05 13:15 UTC, smvdheijden approved these changes

2023-12-05 13:17 UTC, merged