Feature/fdp 1812
OSGP/sng-crest-device-simulator pull request #6
Opened 2023-11-30 15:14 UTC by LucianoFavoroso

2023-11-30 15:40 UTC, jasperkamerling approved these changes

2023-12-01 10:32 UTC, smvdheijden requested changes

2023-12-01 10:32 UTC, smvdheijden commented on application/src/main/resources/messages/kod-alarm-message.json
> +  "TEL": 20316,
Use `20416`.

2023-12-01 10:32 UTC, smvdheijden commented on application/src/main/resources/messages/kod-message.json
> +    0,
Leave value at 3.

2023-12-01 11:51 UTC, jasperkamerling approved these changes

2023-12-01 12:35 UTC, merged